In [3]:
import tensorflow as tf

### Initialization of Tensors

In [28]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print("One Dimension Tensors",x,"\n",end="\n")

x=tf.constant([[1,2,3],[4,5,6]])
print("Two Dimension Tensors",x,"\n",end="\n")

x=tf.ones((3,3))
print("one",x,"\n",end="\n")

x=tf.zeros((2,3))
print("zeros",x,"\n",end="\n")

x=tf.eye(3)
print("Identity Matrix",x,"\n",end="\n")

x=tf.random.normal((3,3),mean=0,stddev=1)
print("Random_Normal",x,"\n",end="\n")

x=tf.random.uniform((1,3),minval=0,maxval=1)
print("Uniform",x,"\n",end="\n")

x=tf.range(start=1,limit=10,delta=2)
print("Rannge",x,"\n",end="\n")

x=tf.cast(x,dtype=tf.float64)
print("Cast",x,"\n",end="\n") ## tf.float(16,32,64),tf.int(16,32,64),if.bool

One Dimension Tensors tf.Tensor([[4.]], shape=(1, 1), dtype=float32) 

Two Dimension Tensors tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

one tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) 

zeros tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32) 

Identity Matrix tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32) 

Random_Normal tf.Tensor(
[[-0.9645931  -0.16777554 -1.869359  ]
 [-0.9685218   0.08949853  0.87292   ]
 [-0.22236216  0.73477834  0.22861889]], shape=(3, 3), dtype=float32) 

Uniform tf.Tensor([[0.42543733 0.60629964 0.7856895 ]], shape=(1, 3), dtype=float32) 

Rannge tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32) 

Cast tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64) 



### Mathematical Operations

In [50]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y) ## x+y can also work
print("Add==>",z,"\n",end="\n")

z=tf.multiply(x,y) ## X*Y can also work
print("multilply==>",z,"\n",end="\n") 

z=tf.divide(x,y)  ## X/Y can also work
print("divide==>",z,"\n",end="\n") 

z=tf.tensordot(x,y,axes=1) ##dot prodcut
print("Dot Product",z,"\n",end="\n") 

x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print("MatMul",z,"\n",end="\n")


Add==> tf.Tensor([10 10 10], shape=(3,), dtype=int32) 

multilply==> tf.Tensor([ 9 16 21], shape=(3,), dtype=int32) 

divide==> tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64) 

Dot Product tf.Tensor(46, shape=(), dtype=int32) 

MatMul tf.Tensor(
[[ 0.02028584 -1.3825288  -0.43613708  1.1907189 ]
 [ 0.21841356 -2.7274714  -0.0795099   2.1014621 ]], shape=(2, 4), dtype=float32) 



### Indexing

In [53]:
x=tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [55]:
indices=tf.constant([0,3]) ## we are providing index of 0 and 2 from x
x_ind=tf.gather(x,indices)
print(x_ind)  ## irt will return 0 and 2 from x

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [62]:
x=tf.constant([[1,2],
              [3,4],
              [5,6],
              [7,8]])
print(x[0,:]) ## first row

print(x[-1,:]) ## last row

print(x[:,-1])## last column

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)


### Reshaping

In [70]:
x=tf.range(9)
print("Original",x)

x=tf.reshape(x,(3,3))
print("Reshape",x)

x=tf.transpose(x,perm=[1,0])
print(x)

Original tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
Reshape tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


## Neural Networks with Sequential and Functional API

In [15]:
import tensorflow as tf
import os
os.environ["TFF_CPP_MIN_LOG_LEVEL"]="2"
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import numpy as np

In [96]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(np.max(x_train))
## flatten the images and then normalize them
x_train=x_train.reshape(-1,28*28)/255
x_test=x_test.reshape(-1,28*28)/255
print(np.max(x_train))

## x_train=tf.convert_to_tensor(x_train) ## no need to do this as tensorflow automatically convert numpy array to tensors

(60000, 28, 28)
(60000,)
255
1.0


## Sequential API (very convenient, not very flexible)
- one input and one output then use this one

In [106]:
# model=keras.Sequential(
#     [
#         ## keras.Input(shape=(28*28)),## optional can be done in below step as well
#         layers.Dense(512,activation="relu",input_shape=(28*28)),
#         layers.Dense(256,activation="relu"),
#         layers.Dense(10),
#     ])

# above and below are the same way

model=keras.Sequential()
model.add(tf.keras.Input(shape=(784)))
model.add(layers.Dense(512,activation="relu"))
# print(model.summary())## common debugging purpose you can use
model.add(layers.Dense(256,activation="relu"))
print(model.summary())
model.add(layers.Dense(10,))

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
             )

model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=True)

model.evaluate(x_test,y_test,batch_size=32,verbose=2)


Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_79 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_80 (Dense)             (None, 256)               131328    
Total params: 533,248
Trainable params: 533,248
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_79 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_80 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_81 (Dense)             (None, 10)                2570      
Total params: 535,8

[0.08130016922950745, 0.9781000018119812]

In [109]:
model.predict(x_test)[1]

array([2.8388565e-12, 1.1138582e-08, 9.9988770e-01, 2.6501693e-06,
       7.0207035e-16, 4.4997297e-14, 1.7891786e-15, 1.2902313e-08,
       2.3956714e-10, 2.4637131e-13], dtype=float32)

### Functional API (A bit more flexible)

In [56]:
inputs=keras.Input(shape=(784),name="INPUT_LAYER")
x=layers.Dense(512,activation="relu",name="FIRST_LAYER")(inputs)
x=layers.Dense(256,activation="relu",name="SECOND_LAYER")(x)
outputs=layers.Dense(10,activation="softmax",name="OUTPUT_LAYER")(x)
model=keras.Model(inputs=inputs,outputs=outputs)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
             )

model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=True)

model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "functional_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
INPUT_LAYER (InputLayer)     [(None, 784)]             0         
_________________________________________________________________
FIRST_LAYER (Dense)          (None, 512)               401920    
_________________________________________________________________
SECOND_LAYER (Dense)         (None, 256)               131328    
_________________________________________________________________
OUTPUT_LAYER (Dense)         (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.3742 - accuracy: 0.9002
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2032 - accuracy: 0.9449
Epoch 3/5
1875/1875 [==================

[0.2302073985338211, 0.9526000022888184]

In [116]:
x_train=np.array([1,2,3,4,5,6,7,8,9])
y_train=np.array([2,4,6,8,10,12,14,16,18])

model=keras.Sequential(
    [
    layers.Dense(1,input_shape=[1]), 
    ])

print(model.summary())
model.compile(
    loss="mean_squared_error",
    optimizer="sgd",
             )
model.fit(x_train,y_train,epochs=100)

print(model.predict([8]))


Model: "sequential_29"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_85 (Dense)             (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 121.3346
Epoch 2/100
1/1 [==============================] - 0s 975us/step - loss: 14.9462
Epoch 3/100
1/1 [==============================] - 0s 0s/step - loss: 1.8557
Epoch 4/100
1/1 [==============================] - 0s 977us/step - loss: 0.2449
Epoch 5/100
1/1 [==============================] - 0s 976us/step - loss: 0.0466
Epoch 6/100
1/1 [==============================] - 0s 0s/step - loss: 0.0220
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.0189
Epoch 8/100
1/1 [==============================] - 0s 977us/step - loss: 0.0184
Epoch 9/100
1/1

1/1 [==============================] - 0s 976us/step - loss: 0.0088
Epoch 98/100
1/1 [==============================] - 0s 976us/step - loss: 0.0087
Epoch 99/100
1/1 [==============================] - 0s 977us/step - loss: 0.0087
Epoch 100/100
1/1 [==============================] - 0s 976us/step - loss: 0.0086
[[15.945435]]


## Convolutional Neural Networks with Sequential and Functional API

In [67]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10

In [70]:
(x_train,y_train),(x_test,y_test)=cifar10.load_data()

print(x_train.shape)
print(y_train.shape)
print(np.max(x_train))

x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255

model=keras.sequential(
    [
        keras.Input(shape=(32,32,3)),
        layers.Conv2D(32,3,padding="valid",activation="relu"),
        layers.MaxPooling2D(pool_size=(2,2)),
        layers.Conv2D(64,3,activation="relu"),
        layers.MaxPooling2D(),
        layers.Conv2D(128,3,activation="relu"),
        layers.Flatten(),
        layer.Dense(64,activation=True),
        layers.Dense(10),        
    ])


model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
             )

(50000, 32, 32, 3)
(50000, 1)
255
